

var test = '<?xml version="1.0" encoding="UTF-8"?> <response> <header> <action value="conversation"/> <sessionid value="ss10603335"/> <userid value="uwcnntpsdbdhbps4xbsimkmtor"/> <debug id=""/> </header> <body> <question> <xul> <dropdown_card id="s:x15339293" typeof="DROPDOWN" xmlns="http://www.cyberobject.com/2012/12/term/ui#" xmlns:s="http://www.cyberobject.com/2012/12/session#ss10603335/ui" xmlns:term="http://www.cyberobject.com/2012/12/term#"> <question typeof="HTML">please choose a disposition code from the list.</question> <dropdown id="s:x5485377" param="disp"> <option id="s:x8044905" value="400">can not be called</option> <option id="s:x8044905" value="710">physical inside premises</option> <option id="s:x8044905" value="800">miscellaneous</option> <option id="s:x8044905" value="303">transmission</option> <option id="s:x8044905" value="516">speed dial</option> <option id="s:x8044905" value="551">call waiting id</option> <option id="s:x8044905" value="570">primary inter-exchange carrier</option> <option id="s:x8044905" value="525">repeat dial</option> <option id="s:x8044905" value="555">feature</option> <option id="s:x8044905" value="514">remote call forwarding</option> <option id="s:x8044905" value="114">multiple lines reported at same location-cellular no</option> <option id="s:x8044905" value="400">can not be called</option> <option id="s:x8044905" value="573">primary inter-exchange carrier</option> <option id="s:x8044905" value="569">can not call long distance</option> <option id="s:x8044905" value="527">automatic call back</option> <option id="s:x8044905" value="985">drop wire</option> <option id="s:x8044905" value="205">can not call out</option> <option id="s:x8044905" value="598">voice mail service</option> <option id="s:x8044905" value="970">isdn defective pair recovery order-ndc use only</option> <option id="s:x8044905" value="524">ring</option> </dropdown> <submit id="s:x14819256" reply="trbl found code is $disp" typeof="BUTTON">Ok</submit> </dropdown_card> </xul> </question> </body> </response>';
var test1 = '<?xml version="1.0" encoding="UTF-8"?> <response> <header> <action value="conversation"/> <sessionid value="d95a43307e504f2581b345834120a9ec"/> <userid value=""/> <debug id=""/> </header> <body> <question> <xul> <dropdown_card typeof="DROPDOWN" xmlns="http://www.cyberobject.com/2012/12/term/ui#" xmlns:s="http://www.cyberobject.com/2012/12/session#ss10603335/ui" xmlns:term="http://www.cyberobject.com/2012/12/term#"> <question typeof="HTML">Choose one:</question> <dropdown param="disp"> <option value="can not be called">can not be called</option> <option value="physical inside premises">physical inside premises</option> <option value="miscellaneous">miscellaneous</option> <option value="transmission">transmission</option> <option value="speed dial">speed dial</option> <option value="call waiting id">call waiting id</option> </dropdown> <submit reply="$disp" typeof="BUTTON">Ok</submit> </dropdown_card> </xul> </question> </body> </response>';

var dropdownTemp ='<?xml version="1.0" encoding="UTF-8"?> <response> <header> <action value="conversation"/> <sessionid value="%s"/> <userid value=""/> <debug id=""/> </header> <body> <question> <xul> <dropdown_card typeof="DROPDOWN" xmlns="http://www.cyberobject.com/2012/12/term/ui#" xmlns:s="http://www.cyberobject.com/2012/12/session#ss10603335/ui" xmlns:term="http://www.cyberobject.com/2012/12/term#"> <question typeof="HTML">%s</question> <dropdown param="disp"> %s </dropdown> <submit reply="$disp" typeof="BUTTON">Ok</submit> </dropdown_card> </xul> </question> </body> </response>';

exports.test = test;
exports.test1 = test1;
exports.dropdownCard = dropdownTemp;
